name: Triggering Github Workflow
run-name: ${{ github.actor }} Running the action
on: [push]
jobs:
  trigger-awx-job:
    runs-on: self-hosted
    steps:
      - name: Print GitHub Context
        run: |
          echo "GitHub Context Data:"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Action: ${{ github.action }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
      # - name: Python Package Installation in Runner
      #   run: pip3 install -r .github/python-requirements-cicd.txt

      # - name: Install CICD Collections
      #   run: ansible-galaxy collection install -r .github/ansible-collections-cicd.yml --force

      # - name: Trigger AWX Job from Runner
      #   run: ansible-playbook /home/user1/git_runner/playbooks/new_run.yml